version: 2

ci_steps: &ci_steps
  steps:
    - checkout

    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

    - run:
        name: Installing dependencies
        command: |
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    - run:
        name: Running tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

          bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results

jobs:
  run_ci_ruby261:
    docker:
      - image: circleci/ruby:2.6.1
    <<: *ci_steps
  run_ci_ruby253:
    docker:
      - image: circleci/ruby:2.5.3
    <<: *ci_steps
  run_ci_ruby238:
    docker:
      - image: circleci/ruby:2.3.8
    <<: *ci_steps

workflows:
  version: 2
  run_ci:
    jobs:
      - run_ci_ruby261
      - run_ci_ruby253
      - run_ci_ruby238
